version: "3.1"
services:
  www:
    build: ./docker/php/
    container_name: "sa-jordan-www"
    ports:
      - 8002:80
    volumes:
      - ./:/var/www/html/
      # - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/php.ini:/usr/local/etc/php/conf.d/override.ini
      - ./docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    links:
      - db
    networks:
      - default
  db:
    build: ./docker/mysql
    container_name: "sa-jordan-db"
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: sa_jordan
      MYSQL_USER: sa_jordan
      MYSQL_PASSWORD: sa_jordan
      MYSQL_ROOT_PASSWORD: sa_jordan
    command:
      [
        mysqld,
        --default-authentication-plugin=mysql_native_password,
        --character-set-server=utf8mb4,
        --collation-server=utf8mb4_unicode_ci,
        --innodb_monitor_enable=all,
        --max-connections=1001,
      ]
    volumes:
      - sa_jordan_volume:/var/lib/mysql
    networks:
      - default
  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Erdem@1905
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"
    networks:
      - default
volumes:
  sa_jordan_volume:
